### PR TITLE
Update name and several function

### PR DESCRIPTION
**Pull request by leeheekyo**
First, modify variable name, and private function name. Second, create several function from complex function. In test case, this code worked well.

### CODE REVIEW

**Comment by padreati** [comment]
I think you should run all tests locally before commit to mainline. And it would be better to avoid adding files which relates with project IDE. Not everybody works with the same IDE.

**Comment by padreati** [comment]
Hi! I approved last commit, but a test was broken. I fix it now. Please run all tests before any commit.

**Comment by leeheekyo** [comment]
Really..? Sorry about that. I will check too.

2017. 5. 4. 오후 11:10에 "Aurelian Tutuianu" <notifications@github.com>님이 작성:

**Comment by leeheekyo** [comment]
You say that TestCase in "ImageGraphicsTest.java" was broken???

**Comment by padreati** [comment]
No. The test in question is tst/rapaio/ml/classifier/rule/OneRuleTest.java

You can find my fix here:
https://github.com/padreati/rapaio/commit/196f1d879ab22e4e241682d6db0d22167684bf27

**Comment by leeheekyo** [comment]
It seems to have happened in a 313-314 line in TextTitle.java.

[image: 본문 이미지 1]

When I tried it, there was no problem in my computer that operated in
Window 8.1, jre 1.8.0_131 and eclipse neon.1, so I sent a request. Sorry I
will be more careful in the future.


2017-05-04 23:32 GMT+09:00 Aurelian Tutuianu <notifications@github.com>:

**Pull request merged**
